### ISSUE TITLE
Segmentation fault when MIDI port specified

### ISSUE THREAD

**Issue by kasbah** [ssj71/reMID.lv2#1]
Hey, very interested in hearing this :smile: .

When I start it up without any arguments it seems to start up ok,  but when I try and connect it, it segfaults. 

```
$ gdb reMID
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
...
Reading symbols from reMID...done.
(gdb) r -m 129:0
Starting program: /home/kaspar/projects/reMID.lv2/build/src/reMID -m 129:0
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
__strcpy_sse2_unaligned ()
    at ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S:605
605 ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __strcpy_sse2_unaligned ()
    at ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S:605
#1  0x0000000000403da2 in add_connect (connect_args=0x7fffffffd780, 
    port=0x7fffffffeb30 "129:0") at /home/kaspar/projects/reMID.lv2/src/reMID.c:25
#2  0x0000000000403ec2 in main (argc=3, argv=0x7fffffffe868)
    at /home/kaspar/projects/reMID.lv2/src/reMID.c:75
```

Let me know if you need any more info.

**Comment by ssj71** [comment]
Good timing, I had a few minutes to work on projects tonight. Thanks for the report. I just pushed an update that should fix that. That feature from the legacy code that I refactored and its not something I use much personally (I always just do connections manually with qjackctl) so it wasn't really tested. Please let me know if it still isn't working.

Have fun with reMID!

**Comment by kasbah** [comment]
Thanks! That did solve the crashing. It doesn't actually seem to connect to any port though. The reason I was trying this in the first place was that reMID doesn't show any MIDI input ports at all, I assumed that was the default. MIDI doesn't seem to be working at all :/

**Comment by ssj71** [comment]
ah, thanks, I rushed this out worse than I thought. I just pushed a change to the build scripts to make midi work again. Its doing jack midi now but if you want it to use the alsa midi driver switch the comment on line 74/75 of src/CMakeLists.txt. Basically at compile time you have to #define either ALSA_MIDI or JACK_MIDI and the scripts were set so neither one was defined and therefore neither got compiled in. At least that's fixed now.

Sorry I don't have more time right now to polish this up. I'll get to it eventually. Keep reporting any issues you find! Right now you'll have to manually set which instrument file you want to load with the -i argument (i.e. reMID -i ~/.config/reMID/instruments.conf). Making it search through the usual paths is on the todo list.
Thanks again.

**Comment by kasbah** [comment]
Ah no worries, I use a2j so I don't really mind which but one is definitely needed :D. I'll give it a play when I get home.

**Comment by kasbah** [comment]
Wow it sounds great! Will be using this all the time. Thanks for your help and for pushing the fixes.

**Comment by ssj71** [comment]
glad you like it :D
Be sure to share if you come up with some really great patches!
