### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by jambonbill** [ssj71/reMID.lv2#7]
please provide some sort of installation instruction, especially around liblv2-dev

**Comment by jambonbill** [comment]
when i 'make' :
```
fatal error: lv2.h: No such file or directory
 #include<lv2.h>

```
so i suppose i have to configure lv2 installation in some ways, but how ?

**Comment by ssj71** [comment]
Thanks for your interest in reMID.lv2. What OS are you using?

On ubuntu type systems you can just open up a terminal and type in `sudo apt-get install lv2-dev`. On other systems the command may be slightly different.

**Comment by jambonbill** [comment]
i'm using ubuntu, but i'm trying to compile the sources, as i'd like to use reMID as standalone

**Comment by ssj71** [comment]
If I understand correctly you are trying to compile the dependencies? I don't really know how the sources of all those projects are configured. That's the point of using system packages is that I don't have to worry about those details. Even if you want to use reMID standalone, you shouldn't need to compile the dependencies yourself. Just install the lv2-dev package using the command I provided above and it will resolve the error you are seeing.

if you really don't want to install the dependencies for the plugin version edit src/CMakeLists.txt to remove line 16 and every command referencing remid.lv2.

**Comment by jambonbill** [comment]
thanks for your help !

**Comment by ssj71** [comment]
glad you got it working. Enjoy!
